# Generated by Django 2.2.4 on 2019-08-30 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JiraTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('status', models.TextField(null=True)),
                ('assignee', models.CharField(max_length=100, null=True)),
                ('created', models.DateTimeField(null=True)),
                ('links', models.ManyToManyField(blank=True, related_name='_jiraticket_links_+', to='myJira.JiraTicket')),
            ],
        ),
    ]
