# Generated by Django 2.2.4 on 2019-09-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myJira', '0003_auto_20190830_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jiraticket',
            name='created',
            field=models.DateField(null=True),
        ),
    ]
