# Generated by Django 2.2.4 on 2019-09-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myJira', '0004_auto_20190905_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jiraticket',
            name='created',
            field=models.DateTimeField(null=True),
        ),
    ]
