# Generated by Django 2.2.4 on 2019-09-05 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myJira', '0005_auto_20190905_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='jiraticket',
            name='Summary',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
